default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: jobjourney_development

test:
  <<: *default
  database: jobjourney_test

staging:
  <<: *default
  database: jobjourney_staging
  username: <%= Rails.application.credentials.STAGING_DB_USERNAME %>
  password: <%= Rails.application.credentials.STAGING_DB_PASSWORD %>

production:
  <<: *default
  database: jobjourney_production
  username: <%= Rails.application.credentials.PRODUCTION_DB_USERNAME %>
  password: <%= Rails.application.credentials.PRODUCTION_DB_PASSWORD %>
